/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author malico
 */
public class VistaResta extends javax.swing.JDialog {

    /**
     * Creates new form VistaSuma
     */
    public VistaResta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getCampoPrimerNumero() {
    	return campoPrimerNumero.getText();    
    }
    public String getCampoSegundoNumero() {
    	return campoSegundoNumero.getText();    
    }
    public void setCampoResultado(String resultado) {
        campoResultado.setText(resultado);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoPrimerNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoSegundoNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoResultado = new javax.swing.JTextField();
        botonRestar = new javax.swing.JButton();
        botonRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resta");
        setBounds(new java.awt.Rectangle(250, 250, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Primer Número");
        getContentPane().add(jLabel1);

        campoPrimerNumero.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoPrimerNumero.setBorder(null);
        campoPrimerNumero.setOpaque(false);
        getContentPane().add(campoPrimerNumero);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Segundo Número");
        getContentPane().add(jLabel2);

        campoSegundoNumero.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoSegundoNumero.setBorder(null);
        campoSegundoNumero.setOpaque(false);
        getContentPane().add(campoSegundoNumero);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3);

        campoResultado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoResultado.setBorder(null);
        campoResultado.setOpaque(false);
        getContentPane().add(campoResultado);

        botonRestar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonRestar.setText("Restar");
        getContentPane().add(botonRestar);

        botonRetornar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonRetornar.setText("Retornar");
        getContentPane().add(botonRetornar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonRestar;
    public javax.swing.JButton botonRetornar;
    private javax.swing.JTextField campoPrimerNumero;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JTextField campoSegundoNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
